export const ActionTypes = {
  SET_OFFERS: 'SET_OFFERS',
  SELECTED_OFFER: 'SELECTED_OFFER',
};

// OFFER_LIST_REQUEST = 'OFFER_LIST_REQUEST',
//     OFFER_LIST_SUCCESS = 'OFFER_LIST_SUCCESS',
//     OFFER_LIST_FAIL = 'OFFER_LIST_FAIL'
